# Generated by Django 2.0.2 on 2018-03-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_add_addresses_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_on_hand',
            field=models.IntegerField(default=1),
        ),
    ]
