# Generated by Django 2.0.2 on 2018-03-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_add_receipts_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='product_count',
            new_name='quantity',
        ),
    ]
