# Generated by Django 2.0.2 on 2018-03-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_product_count_to_quantity-receipts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventory_on_hand',
            new_name='inventory',
        ),
    ]
