# Generated by Django 2.0.2 on 2018-03-22 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_alter_inventory_on_hand_to_inventory-products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Must enter a valid 5 digit zip code', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='confirmation_code',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8),
        ),
    ]
