# Generated by Django 2.0.2 on 2018-03-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_positive_ints_only-products_receipts_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
